name: Build

on:
  push:
  pull_request:
  merge_group:

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest]
        include:
        - os: ubuntu-latest
          cmake-init-env: CXXFLAGS=-Werror
        - os: macOS-latest
          cmake-init-env: CXXFLAGS=-Werror

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Prepare Linux
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pkg-config cmake build-essential libsdl2-dev libsdl2-image-dev

    - name: Prepare macOS
      if: contains(matrix.os, 'macOS')
      run: |
        brew update || true
        brew install pkg-config cmake sdl2 SDL2_image || true
        sudo rm -rf /Library/Developer/CommandLineTools

    - name: Build in debug mode
      run: |
        mkdir debug
        cd debug
        ${{ matrix.cmake-path }}cmake -E env ${{ matrix.cmake-init-env }} ${{ matrix.cmake-path }}cmake ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=Debug -Werror=dev ..
        ${{ matrix.cmake-path }}cmake --build . --config Debug ${{ matrix.build-args }}

    - name: Build in release mode
      run: |
        mkdir release
        cd release
        ${{ matrix.cmake-path }}cmake -E env ${{ matrix.cmake-init-env }} ${{ matrix.cmake-path }}cmake ${{ matrix.cmake-args }} -DCMAKE_BUILD_TYPE=Release -Werror=dev ..
        ${{ matrix.cmake-path }}cmake --build . --config Release ${{ matrix.build-args }}

